# Generated by Django 3.1.6 on 2021-02-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210218_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rating',
            new_name='newPrice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='countStock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='numReviews',
        ),
        migrations.AddField(
            model_name='product',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
